### ISSUE TITLE
Please add a license so that others can use this package

### ISSUE THREAD

**Issue by levinse** [copleykj/socialize-server-time#1]
Could you please add a license so that others can use this package? Thanks

**Comment by levinse** [comment]
For clarity, in case you're unaware, publishing software without a license means that anyone attempting to use it would be in violation of copyright. If you can add a MIT or other distribution friendly license, that would be appreciated!

**Comment by copleykj** [comment]
I've been thinking about this and I'm leaning towards AGPL3? Is this distribution friendly enough?

**Comment by levinse** [comment]
Hi, thanks for the response. GPL-based licenses would, in most circumstances, force anyone using this package to release the source code of anything that uses this package. Most meteor packages are therefore licensed under MIT to avoid this. Would you consider using MIT?

**Comment by dgacitua** [comment]
Personally, I want to use this package in my project, but the licensing issue is stopping me to do so. I'd like to see this package properly licensed. Thank you for your work.

**Comment by copleykj** [comment]
Should be all set.
